/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pwukaoyoznleilitycpt";
export const supabaseUrl = `https://${projectId}.supabase.co`;
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3dWthb3lvem5sZWlsaXR5Y3B0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5OTY4NjIsImV4cCI6MjA3NzU3Mjg2Mn0.mDvEqemYwPm5Yxd_p9gvIflrJFkHHHFRDZ8uNKqHW9E";